In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from PIL import Image
import os
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
#load the all the images lcoated int eh folder dill and convert them to numpy arrays

all_images = []
for filename in os.listdir("/home/jouell/code/jouell3/plant_detect/data/raw/dill"):
    if filename.endswith(".jpg"):     
        image = Image.open("/home/jouell/code/jouell3/plant_detect/data/raw/dill/" + filename)
        # save the image with a new name
        #with Image.open("/home/jouell/code/jouell3/plant_detect/data/raw/dill/" + filename) as img:
        #    img.save("/home/jouell/code/jouell3/plant_detect/data/raw/dill/" + f"dill_{filename}")
        image_np = np.array(image)
        all_images.append(image_np)
all_images = np.array(all_images)
all_images.shape

In [26]:
## this allow allow to rename all teh images located in a folder with the name of the folder as prefix, for example dill_0.jpg, dill_1.jpg, etc.

from pathlib import Path

folder = Path("/home/jouell/code/jouell3/plant_detect/data/raw/lavender")
prefix = folder.name

for path in sorted(folder.glob("*.jpg")):
    if not path.stem.startswith(f"{prefix}_"):  # skip already-renamed files
        new_path = path.parent / f"{prefix}_{path.name}"
        path.rename(new_path)
        print(f"{path.name} → {new_path.name}")

print("Done.")

0.jpg → lavender_0.jpg
1.jpg → lavender_1.jpg
10.jpg → lavender_10.jpg
100.jpg → lavender_100.jpg
101.jpg → lavender_101.jpg
102.jpg → lavender_102.jpg
103.jpg → lavender_103.jpg
104.jpg → lavender_104.jpg
105.jpg → lavender_105.jpg
106.jpg → lavender_106.jpg
107.jpg → lavender_107.jpg
108.jpg → lavender_108.jpg
109.jpg → lavender_109.jpg
11.jpg → lavender_11.jpg
110.jpg → lavender_110.jpg
111.jpg → lavender_111.jpg
112.jpg → lavender_112.jpg
113.jpg → lavender_113.jpg
114.jpg → lavender_114.jpg
115.jpg → lavender_115.jpg
116.jpg → lavender_116.jpg
117.jpg → lavender_117.jpg
118.jpg → lavender_118.jpg
119.jpg → lavender_119.jpg
12.jpg → lavender_12.jpg
120.jpg → lavender_120.jpg
121.jpg → lavender_121.jpg
122.jpg → lavender_122.jpg
123.jpg → lavender_123.jpg
124.jpg → lavender_124.jpg
125.jpg → lavender_125.jpg
126.jpg → lavender_126.jpg
127.jpg → lavender_127.jpg
128.jpg → lavender_128.jpg
129.jpg → lavender_129.jpg
13.jpg → lavender_13.jpg
130.jpg → lavender_130.jpg
131.jpg → lavender_131.jpg
132.jpg → lavender_132.jpg
133.jpg → lavender_133.jpg
134.jpg → lavender_134.jpg
135.jpg → lavender_135.jpg
136.jpg → lavender_136.jpg
137.jpg → lavender_137.jpg
138.jpg → lavender_138.jpg
139.jpg → lavender_139.jpg
14.jpg → lavender_14.jpg
140.jpg → lavender_140.jpg
141.jpg → lavender_141.jpg
142.jpg → lavender_142.jpg
143.jpg → lavender_143.jpg
144.jpg → lavender_144.jpg
145.jpg → lavender_145.jpg
146.jpg → lavender_146.jpg
147.jpg → lavender_147.jpg
148.jpg → lavender_148.jpg
149.jpg → lavender_149.jpg
15.jpg → lavender_15.jpg
150.jpg → lavender_150.jpg
151.jpg → lavender_151.jpg
152.jpg → lavender_152.jpg
153.jpg → lavender_153.jpg
154.jpg → lavender_154.jpg
155.jpg → lavender_155.jpg
156.jpg → lavender_156.jpg
157.jpg → lavender_157.jpg
158.jpg → lavender_158.jpg
159.jpg → lavender_159.jpg
16.jpg → lavender_16.jpg
160.jpg → lavender_160.jpg
161.jpg → lavender_161.jpg
162.jpg → lavender_162.jpg
163.jpg → lavender_163.jpg
164.jpg → lavender_164.jpg
165.jpg → lavender_165.jpg
166.jpg → lavender_166.jpg
167.jpg → lavender_167.jpg
168.jpg → lavender_168.jpg
169.jpg → lavender_169.jpg
17.jpg → lavender_17.jpg
170.jpg → lavender_170.jpg
171.jpg → lavender_171.jpg
172.jpg → lavender_172.jpg
173.jpg → lavender_173.jpg
174.jpg → lavender_174.jpg
175.jpg → lavender_175.jpg
176.jpg → lavender_176.jpg
177.jpg → lavender_177.jpg
178.jpg → lavender_178.jpg
179.jpg → lavender_179.jpg
18.jpg → lavender_18.jpg
180.jpg → lavender_180.jpg
181.jpg → lavender_181.jpg
182.jpg → lavender_182.jpg
183.jpg → lavender_183.jpg
184.jpg → lavender_184.jpg
185.jpg → lavender_185.jpg
186.jpg → lavender_186.jpg
187.jpg → lavender_187.jpg
188.jpg → lavender_188.jpg
189.jpg → lavender_189.jpg
19.jpg → lavender_19.jpg
190.jpg → lavender_190.jpg
191.jpg → lavender_191.jpg
192.jpg → lavender_192.jpg
193.jpg → lavender_193.jpg
194.jpg → lavender_194.jpg
195.jpg → lavender_195.jpg
196.jpg → lavender_196.jpg
197.jpg → lavender_197.jpg
198.jpg → lavender_198.jpg
199.jpg → lavender_199.jpg
2.jpg → lavender_2.jpg
20.jpg → lavender_20.jpg
200.jpg → lavender_200.jpg
201.jpg → lavender_201.jpg
202.jpg → lavender_202.jpg
203.jpg → lavender_203.jpg
204.jpg → lavender_204.jpg
205.jpg → lavender_205.jpg
206.jpg → lavender_206.jpg
207.jpg → lavender_207.jpg
208.jpg → lavender_208.jpg
209.jpg → lavender_209.jpg
21.jpg → lavender_21.jpg
210.jpg → lavender_210.jpg
211.jpg → lavender_211.jpg
212.jpg → lavender_212.jpg
213.jpg → lavender_213.jpg
214.jpg → lavender_214.jpg
215.jpg → lavender_215.jpg
216.jpg → lavender_216.jpg
217.jpg → lavender_217.jpg
218.jpg → lavender_218.jpg
219.jpg → lavender_219.jpg
22.jpg → lavender_22.jpg
220.jpg → lavender_220.jpg
221.jpg → lavender_221.jpg
222.jpg → lavender_222.jpg
223.jpg → lavender_223.jpg
224.jpg → lavender_224.jpg
225.jpg → lavender_225.jpg
226.jpg → lavender_226.jpg
227.jpg → lavender_227.jpg
228.jpg → lavender_228.jpg
229.jpg → lavender_229.jpg
23.jpg → lavender_23.jpg
230.jpg → lavender_230.jpg
231.jpg → lavender_231.jpg
232.jpg → lavender_232.jpg
233.jpg → lavender_233.jpg
234.jpg → lavender_234.jpg
235.jpg → lavender_235.jpg
236.jpg → lavender_236.jpg
237.jpg → lavender_237.jpg
238.jpg → lavender_238.jpg
239.jpg → lavender_239.jpg
24.jpg → lavender_24.jpg
240.jpg → lavender_240.jpg
241.jpg → lavender_241.jpg
242.jpg → lavender_242.jpg
243.jpg → lavender_243.jpg
244.jpg → lavender_244.jpg
245.jpg → lavender_245.jpg
246.jpg → lavender_246.jpg
247.jpg → lavender_247.jpg
248.jpg → lavender_248.jpg
249.jpg → lavender_249.jpg
25.jpg → lavender_25.jpg
250.jpg → lavender_250.jpg
251.jpg → lavender_251.jpg
252.jpg → lavender_252.jpg
253.jpg → lavender_253.jpg
254.jpg → lavender_254.jpg
255.jpg → lavender_255.jpg
256.jpg → lavender_256.jpg
257.jpg → lavender_257.jpg
258.jpg → lavender_258.jpg
259.jpg → lavender_259.jpg
26.jpg → lavender_26.jpg
260.jpg → lavender_260.jpg
261.jpg → lavender_261.jpg
262.jpg → lavender_262.jpg
263.jpg → lavender_263.jpg
264.jpg → lavender_264.jpg
265.jpg → lavender_265.jpg
266.jpg → lavender_266.jpg
267.jpg → lavender_267.jpg
268.jpg → lavender_268.jpg
269.jpg → lavender_269.jpg
27.jpg → lavender_27.jpg
270.jpg → lavender_270.jpg
271.jpg → lavender_271.jpg
272.jpg → lavender_272.jpg
273.jpg → lavender_273.jpg
274.jpg → lavender_274.jpg
275.jpg → lavender_275.jpg
276.jpg → lavender_276.jpg
277.jpg → lavender_277.jpg
278.jpg → lavender_278.jpg
279.jpg → lavender_279.jpg
28.jpg → lavender_28.jpg
280.jpg → lavender_280.jpg
281.jpg → lavender_281.jpg
282.jpg → lavender_282.jpg
283.jpg → lavender_283.jpg
284.jpg → lavender_284.jpg
285.jpg → lavender_285.jpg
286.jpg → lavender_286.jpg
287.jpg → lavender_287.jpg
288.jpg → lavender_288.jpg
289.jpg → lavender_289.jpg
29.jpg → lavender_29.jpg
290.jpg → lavender_290.jpg
291.jpg → lavender_291.jpg
292.jpg → lavender_292.jpg
293.jpg → lavender_293.jpg
294.jpg → lavender_294.jpg
295.jpg → lavender_295.jpg
296.jpg → lavender_296.jpg
297.jpg → lavender_297.jpg
298.jpg → lavender_298.jpg
299.jpg → lavender_299.jpg
3.jpg → lavender_3.jpg
30.jpg → lavender_30.jpg
300.jpg → lavender_300.jpg
301.jpg → lavender_301.jpg
302.jpg → lavender_302.jpg
303.jpg → lavender_303.jpg
304.jpg → lavender_304.jpg
305.jpg → lavender_305.jpg
306.jpg → lavender_306.jpg
307.jpg → lavender_307.jpg
308.jpg → lavender_308.jpg
309.jpg → lavender_309.jpg
31.jpg → lavender_31.jpg
310.jpg → lavender_310.jpg
311.jpg → lavender_311.jpg
312.jpg → lavender_312.jpg
313.jpg → lavender_313.jpg
314.jpg → lavender_314.jpg
315.jpg → lavender_315.jpg
316.jpg → lavender_316.jpg
317.jpg → lavender_317.jpg
318.jpg → lavender_318.jpg
319.jpg → lavender_319.jpg
32.jpg → lavender_32.jpg
320.jpg → lavender_320.jpg
321.jpg → lavender_321.jpg
322.jpg → lavender_322.jpg
323.jpg → lavender_323.jpg
324.jpg → lavender_324.jpg
325.jpg → lavender_325.jpg
326.jpg → lavender_326.jpg
327.jpg → lavender_327.jpg
328.jpg → lavender_328.jpg
329.jpg → lavender_329.jpg
33.jpg → lavender_33.jpg
330.jpg → lavender_330.jpg
331.jpg → lavender_331.jpg
332.jpg → lavender_332.jpg
333.jpg → lavender_333.jpg
334.jpg → lavender_334.jpg
335.jpg → lavender_335.jpg
336.jpg → lavender_336.jpg
337.jpg → lavender_337.jpg
338.jpg → lavender_338.jpg
339.jpg → lavender_339.jpg
34.jpg → lavender_34.jpg
340.jpg → lavender_340.jpg
341.jpg → lavender_341.jpg
342.jpg → lavender_342.jpg
343.jpg → lavender_343.jpg
344.jpg → lavender_344.jpg
345.jpg → lavender_345.jpg
346.jpg → lavender_346.jpg
347.jpg → lavender_347.jpg
348.jpg → lavender_348.jpg
349.jpg → lavender_349.jpg
35.jpg → lavender_35.jpg
350.jpg → lavender_350.jpg
351.jpg → lavender_351.jpg
352.jpg → lavender_352.jpg
353.jpg → lavender_353.jpg
354.jpg → lavender_354.jpg
355.jpg → lavender_355.jpg
356.jpg → lavender_356.jpg
357.jpg → lavender_357.jpg
358.jpg → lavender_358.jpg
359.jpg → lavender_359.jpg
36.jpg → lavender_36.jpg
360.jpg → lavender_360.jpg
361.jpg → lavender_361.jpg
362.jpg → lavender_362.jpg
363.jpg → lavender_363.jpg
364.jpg → lavender_364.jpg
365.jpg → lavender_365.jpg
366.jpg → lavender_366.jpg
367.jpg → lavender_367.jpg
368.jpg → lavender_368.jpg
369.jpg → lavender_369.jpg
37.jpg → lavender_37.jpg
370.jpg → lavender_370.jpg
371.jpg → lavender_371.jpg
372.jpg → lavender_372.jpg
373.jpg → lavender_373.jpg
374.jpg → lavender_374.jpg
375.jpg → lavender_375.jpg
376.jpg → lavender_376.jpg
377.jpg → lavender_377.jpg
378.jpg → lavender_378.jpg
379.jpg → lavender_379.jpg
38.jpg → lavender_38.jpg
380.jpg → lavender_380.jpg
381.jpg → lavender_381.jpg
382.jpg → lavender_382.jpg
383.jpg → lavender_383.jpg
384.jpg → lavender_384.jpg
385.jpg → lavender_385.jpg
386.jpg → lavender_386.jpg
387.jpg → lavender_387.jpg
388.jpg → lavender_388.jpg
389.jpg → lavender_389.jpg
39.jpg → lavender_39.jpg
390.jpg → lavender_390.jpg
391.jpg → lavender_391.jpg
392.jpg → lavender_392.jpg
393.jpg → lavender_393.jpg
394.jpg → lavender_394.jpg
395.jpg → lavender_395.jpg
396.jpg → lavender_396.jpg
397.jpg → lavender_397.jpg
398.jpg → lavender_398.jpg
399.jpg → lavender_399.jpg
4.jpg → lavender_4.jpg
40.jpg → lavender_40.jpg
400.jpg → lavender_400.jpg
401.jpg → lavender_401.jpg
402.jpg → lavender_402.jpg
403.jpg → lavender_403.jpg
404.jpg → lavender_404.jpg
405.jpg → lavender_405.jpg
406.jpg → lavender_406.jpg
407.jpg → lavender_407.jpg
408.jpg → lavender_408.jpg
409.jpg → lavender_409.jpg
41.jpg → lavender_41.jpg
410.jpg → lavender_410.jpg
411.jpg → lavender_411.jpg
412.jpg → lavender_412.jpg
413.jpg → lavender_413.jpg
414.jpg → lavender_414.jpg
415.jpg → lavender_415.jpg
416.jpg → lavender_416.jpg
417.jpg → lavender_417.jpg
418.jpg → lavender_418.jpg
419.jpg → lavender_419.jpg
42.jpg → lavender_42.jpg
420.jpg → lavender_420.jpg
421.jpg → lavender_421.jpg
422.jpg → lavender_422.jpg
423.jpg → lavender_423.jpg
424.jpg → lavender_424.jpg
425.jpg → lavender_425.jpg
426.jpg → lavender_426.jpg
427.jpg → lavender_427.jpg
428.jpg → lavender_428.jpg
429.jpg → lavender_429.jpg
43.jpg → lavender_43.jpg
430.jpg → lavender_430.jpg
431.jpg → lavender_431.jpg
432.jpg → lavender_432.jpg
433.jpg → lavender_433.jpg
434.jpg → lavender_434.jpg
435.jpg → lavender_435.jpg
436.jpg → lavender_436.jpg
437.jpg → lavender_437.jpg
438.jpg → lavender_438.jpg
439.jpg → lavender_439.jpg
44.jpg → lavender_44.jpg
440.jpg → lavender_440.jpg
441.jpg → lavender_441.jpg
442.jpg → lavender_442.jpg
443.jpg → lavender_443.jpg
444.jpg → lavender_444.jpg
445.jpg → lavender_445.jpg
446.jpg → lavender_446.jpg
447.jpg → lavender_447.jpg
448.jpg → lavender_448.jpg
449.jpg → lavender_449.jpg
45.jpg → lavender_45.jpg
450.jpg → lavender_450.jpg
451.jpg → lavender_451.jpg
452.jpg → lavender_452.jpg
453.jpg → lavender_453.jpg
454.jpg → lavender_454.jpg
455.jpg → lavender_455.jpg
456.jpg → lavender_456.jpg
457.jpg → lavender_457.jpg
458.jpg → lavender_458.jpg
459.jpg → lavender_459.jpg
46.jpg → lavender_46.jpg
460.jpg → lavender_460.jpg
461.jpg → lavender_461.jpg
462.jpg → lavender_462.jpg
463.jpg → lavender_463.jpg
464.jpg → lavender_464.jpg
465.jpg → lavender_465.jpg
466.jpg → lavender_466.jpg
467.jpg → lavender_467.jpg
468.jpg → lavender_468.jpg
469.jpg → lavender_469.jpg
47.jpg → lavender_47.jpg
470.jpg → lavender_470.jpg
471.jpg → lavender_471.jpg
472.jpg → lavender_472.jpg
473.jpg → lavender_473.jpg
474.jpg → lavender_474.jpg
475.jpg → lavender_475.jpg
476.jpg → lavender_476.jpg
477.jpg → lavender_477.jpg
478.jpg → lavender_478.jpg
479.jpg → lavender_479.jpg
48.jpg → lavender_48.jpg
480.jpg → lavender_480.jpg
481.jpg → lavender_481.jpg
482.jpg → lavender_482.jpg
483.jpg → lavender_483.jpg
484.jpg → lavender_484.jpg
485.jpg → lavender_485.jpg
486.jpg → lavender_486.jpg
487.jpg → lavender_487.jpg
488.jpg → lavender_488.jpg
489.jpg → lavender_489.jpg
49.jpg → lavender_49.jpg
490.jpg → lavender_490.jpg
491.jpg → lavender_491.jpg
492.jpg → lavender_492.jpg
493.jpg → lavender_493.jpg
494.jpg → lavender_494.jpg
495.jpg → lavender_495.jpg
496.jpg → lavender_496.jpg
497.jpg → lavender_497.jpg
498.jpg → lavender_498.jpg
499.jpg → lavender_499.jpg
5.jpg → lavender_5.jpg
50.jpg → lavender_50.jpg
51.jpg → lavender_51.jpg
52.jpg → lavender_52.jpg
53.jpg → lavender_53.jpg
54.jpg → lavender_54.jpg
55.jpg → lavender_55.jpg
56.jpg → lavender_56.jpg
57.jpg → lavender_57.jpg
58.jpg → lavender_58.jpg
59.jpg → lavender_59.jpg
6.jpg → lavender_6.jpg
60.jpg → lavender_60.jpg
61.jpg → lavender_61.jpg
62.jpg → lavender_62.jpg
63.jpg → lavender_63.jpg
64.jpg → lavender_64.jpg
65.jpg → lavender_65.jpg
66.jpg → lavender_66.jpg
67.jpg → lavender_67.jpg
68.jpg → lavender_68.jpg
69.jpg → lavender_69.jpg
7.jpg → lavender_7.jpg
70.jpg → lavender_70.jpg
71.jpg → lavender_71.jpg
72.jpg → lavender_72.jpg
73.jpg → lavender_73.jpg
74.jpg → lavender_74.jpg
75.jpg → lavender_75.jpg
76.jpg → lavender_76.jpg
77.jpg → lavender_77.jpg
78.jpg → lavender_78.jpg
79.jpg → lavender_79.jpg
8.jpg → lavender_8.jpg
80.jpg → lavender_80.jpg
81.jpg → lavender_81.jpg
82.jpg → lavender_82.jpg
83.jpg → lavender_83.jpg
84.jpg → lavender_84.jpg
85.jpg → lavender_85.jpg
86.jpg → lavender_86.jpg
87.jpg → lavender_87.jpg
88.jpg → lavender_88.jpg
89.jpg → lavender_89.jpg
9.jpg → lavender_9.jpg
90.jpg → lavender_90.jpg
91.jpg → lavender_91.jpg
92.jpg → lavender_92.jpg
93.jpg → lavender_93.jpg
94.jpg → lavender_94.jpg
95.jpg → lavender_95.jpg
96.jpg → lavender_96.jpg
97.jpg → lavender_97.jpg
98.jpg → lavender_98.jpg
99.jpg → lavender_99.jpg
Done.

In [27]:
labels = pd.read_csv("/home/jouell/code/jouell3/plant_detect/data/label3.csv")
labels.head()

                         filename label    name
0  data/raw/chives/chives_100.jpg  good  chives
1  data/raw/chives/chives_106.jpg  good  chives
2   data/raw/chives/chives_11.jpg  good  chives
3  data/raw/chives/chives_112.jpg  good  chives
4  data/raw/chives/chives_114.jpg  good  chives

In [28]:
project_root = Path("/home/jouell/code/jouell3/plant_detect")
out_dir = project_root / "data/raw/all_images"
out_dir.mkdir(parents=True, exist_ok=True)



for i, row in labels.iterrows():
    src = project_root / row.filename
    dst = out_dir / Path(row.filename).name
    with Image.open(src) as image:
        image.save(dst)

In [ ]:
labels.nunique()

In [ ]:
labels.to_csv(project_root / "data/labels2.csv", index=False)

In [10]:
labels_2 = pd.read_csv("/home/jouell/code/jouell3/plant_detect/data/labels2.csv")
labels_2.head()

                                            filename label   name
0  notebooks/dataset_aromatic_duckduckgo/aneth/an...  good  aneth
1  notebooks/dataset_aromatic_duckduckgo/aneth/an...  good  aneth
2  notebooks/dataset_aromatic_duckduckgo/aneth/an...  good  aneth
3  notebooks/dataset_aromatic_duckduckgo/aneth/an...  good  aneth
4  notebooks/dataset_aromatic_duckduckgo/aneth/an...  good  aneth

In [13]:
for i, row in enumerate(labels_2.itertuples()):
    name = row.filename.split("/")[-1]
    new_name = name.split("_")[0]
    labels_2.at[i, 'name'] = new_name
    print(labels_2.at[i, 'name'])

aneth
aneth
aneth
aneth
aneth
aneth
aneth
aneth
aneth
aneth
aneth
aneth
aneth
aneth
aneth
aneth
aneth
aneth
aneth
aneth
aneth
aneth
aneth
aneth
aneth
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
chives
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
coriander
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
dill
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
mint
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
oregano
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
parsley
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
rosemary
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
savory
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
tarragon
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
thyme
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
menthe
origan
origan
origan
origan
origan
origan
origan
origan
origan
origan
origan
origan
origan
origan
origan
origan
origan
origan
origan
origan
origan
persil
persil
persil
persil
persil
persil
persil
persil
persil
persil
persil
persil
persil
persil
persil
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
romarin
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
thym
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
coriandre1
menthe1
menthe1
menthe1
menthe1
menthe1
menthe1
menthe1
menthe1
menthe1
menthe1
menthe1
menthe1
menthe1
menthe1
menthe1
menthe1
menthe1
menthe1
menthe1
menthe1
menthe1
origan1
origan1
origan1
origan1
origan1
origan1
origan1
origan1
origan1
origan1
origan1
origan1
origan1
origan1
origan1
origan1
origan1
origan1
origan1
origan1
origan1
origan1
origan1
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
angelica
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
borage
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
chamomille
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel
fennel

In [15]:
labels_2.to_csv("/home/jouell/code/jouell3/plant_detect/data/labels2.csv", index=False)